{
 "title": "Water Monitoring System",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Gallons Gained/Used Over Selected Time Period",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gallons Used",
   "type": "gauge",
   "description": "Basing on approx 60 gallons used per person per day",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsOut",
     "query": "SELECT \"value\" FROM \"gallonsOut\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsIn",
     "query": "SELECT \"value\" FROM \"gallonsIn\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained/Used Over Fixed Time Periods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gallons Gained (Today)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsIn",
     "query": "SELECT \"value\" FROM \"gallonsIn\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained (Yesterday)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsIn",
     "query": "SELECT \"value\" FROM \"gallonsIn\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained (2 Days Ago)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsIn",
     "query": "SELECT \"value\" FROM \"gallonsIn\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained (3 Days Ago)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsIn",
     "query": "SELECT \"value\" FROM \"gallonsIn\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained (Last 7 Days)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "gallonsIn",
     "query": "SELECT \"value\" FROM \"gallonsIn\" WHERE $timeFilter AND (value > 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained/Used Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gallons Used",
   "type": "graph",
   "description": "Gallons of water drained from the tank, being used by the house. Ex: toilets, faucets, showers, etc. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "gallons", "label": "Gallons" }
   ],
   "targets": [
    {
     "alias": "Gallons",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" }
     ],
     "measurement": "gallonsOut",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gallons Gained",
   "type": "graph",
   "description": "Gallons/Minute (GPM) of water being added to the tank, coming into the house. Source: the well.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "gallons", "label": "Gallons" }
   ],
   "targets": [
    {
     "alias": "Gallons",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" }
     ],
     "measurement": "gallonsIn",
     "query": "SELECT mean(\"value\") FROM \"gallonsIn\" WHERE $timeFilter GROUP BY time(2s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Rate In/Out Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Flow Rate Out",
   "type": "graph",
   "description": "Gallons/Minute (GPM) of water draining from the tank, being used by the house. Ex: toilets, faucets, showers, etc. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "GPM" }
   ],
   "targets": [
    {
     "alias": "GPM",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" }
     ],
     "measurement": "flowRateOut",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow Rate In",
   "type": "graph",
   "description": "Gallons/Minute (GPM) of water being added to the tank, coming into the house. Source: the well.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "flowgpm", "label": "GPM" }
   ],
   "targets": [
    {
     "alias": "GPM",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" }
     ],
     "measurement": "flowRateIn",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}